### ISSUE TITLE
Update documentation

### ISSUE THREAD

**Issue by joelalejandro** [ebryn/jsonapi-ts#107]
Outdated sections:

- [x] Relationships (#153)
- [x] Schema definition (need to talk about primaryKeyName) (#153)
- [x] Authentication/Authorization (#153)

Missing sections:

- [x] Bulk operations (#151)
- [x] WebSocket support  
  - [x] Using the jsonApiWebSocket handler (#151)
  - [x] Authenticating on WebSockets (#159)
- [x] Addons (#152)
- [x] Serialization (#160)
