### ISSUE TITLE
Implement built-in authorization

### ISSUE THREAD

**Issue by joelalejandro** [ebryn/jsonapi-ts#111]
- [x] User login (via session:add) (#112)
- [x] User get (#112)
- [x] `@Authorize` working with new user processor (#112)
- [x] User sign up (#113)
